meta_rep = 1
stat_fn = ["mean", "med"]
res_dir = "res-hpc-bo"
algo = "bo"

######################
###### Metrics #######
######################
[metrics]

[[metrics.simple]]
id = "goal"

######################
##### Benchmarks #####
######################

[[benchmarks]]
name = "HPC-benchmarks"
id = "hpc-bench"
root_dir = "hpc"
compile_cmd = "cd hpc; python3 setup.py > tmp"

[[benchmarks.apps]]
name = "CG"
id = "CG"
root_dir = "NPB3.0-omp-C/CG"
exec_cmd = "run.sh"
compile_cmd = "make CLASS=A CCC=clang MODE=<compile_flags>"
variants = [""]

######################
####### Space ########
######################

[exploration-space]

[[exploration-space.execflags]]
name = ""
values = [""]

######################

[[exploration-space.compileflags]]
name = "-O3"

[[exploration-space.compileflags]]
name = "-O2"

[[exploration-space.compileflags]]
name = "-ffast-math"

[[exploration-space.compileflags]]
name = "-march=native"

######################

# When the bench supports OMP
[[exploration-space.envvars]]
name = "OMP_NUM_THREADS"
id = "th"
values = [8,16,24]

[[exploration-space.envvars]]
name = "SPX_PKG_FIRST"
id = "pkg"
values = [0,1]

[[exploration-space.envvars]]
name = "SPX_SMT_FIRST"
id = "smt"
values = [0,1]


# Not relevant for dahu grid architectures
###
[[exploration-space.envvars]]
name = "SPX_DIE_FIRST"
id = "die"
values = [0, 1]

[[exploration-space.envvars]]
name = "SPX_L3_FIRST"
id = "l3"
values = [0, 1]
###

######################

# When we have sudo rights to activate and deactivate prefetchers
[[exploration-space.envcmd]]
name = "sudo /usr/sbin/wrmsr -a 0x1A4 "
id = "1A4pref-"
values = ['0x00','0x20','0x10','0x30','0x08','0x28','0x18','0x38','0x04', 
        '0x24','0x14','0x34','0x0c','0x2c','0x1c','0x3c','0x01','0x21', 
        '0x11','0x31','0x09','0x29','0x19','0x39','0x05','0x25','0x15', 
        '0x35','0x0d','0x2d','0x1d','0x3d']
reset = 0


[[exploration-space.envcmd]]
name = "sudo /usr/sbin/wrmsr -a 0x1320"
id = "1320pref-"
values = ['0x108837ea470906c4', '0x10883fea470906c4']
reset = 0x108837ea470906c4


[[exploration-space.envcmd]]
name = "sudo /usr/sbin/wrmsr -a 0x1321"
id = "1321pref-"
values = ['0x161122147800', '0x171122147800']
reset = 0x171122147800



[[exploration-space.envcmd]]
# this path should be changed to an absolute value -- todo
name = "sudo /home/uartdev/behnaz/corhpex-share/example/hpc/p_freq.sh"
id = "Pfreq"
values = ["1500MHz", "2000MHz", "3000MHz", "3500MHz", "4000MHz", "4500MHz", "5000MHz"]
reset = "3200MHz"


[[exploration-space.envcmd]]
name = "sudo /home/uartdev/behnaz/corhpex-share/example/hpc/e_freq.sh"
id = "Efreq"
values = ["1000MHz", "1500MHz", "2000MHz", "3200MHz", "3500MHz", "4000MHz", "4600MHz"]
reset = "3000MHz"


# example of bo exploration parameters
[algo_params]
init_points=50                      # number of random points to start with
n_iter=150                           # number of iterations (i.e. number of points on top of the random one at the start)
alpha=0.0001                        # tune the gaussian process regressor, use higher values for decrete parameters
aquisition_func.kind = "ei"         # or "ucb" or 'poi'
aquisition_func.xi = 3              # or kappa for ucb
target = "goal"                      # target metric to optimize, could be rdtsc or energy
target_stat = "med"                 # statistic of the metric to optimize
seed_value = 0                      # seed value for anything random in the algorithm
